server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  datasource:
    url: jdbc:mysql://114.116.240.82:3306/spring_learn?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: learn
    password: learn@123456
  security:
    oauth2:
      authorization-server:
        client:
          oidc-client:
            registration:
              client-id: "learn-web"
              client-secret: "{noop}web@123456"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/login"
              scopes:
                - "openid"
                - "profile"
                - "web.read"
                - "web.write"
            require-authorization-consent: true

